Refactor setup script
Why:

* It is not using asdf-vm to install the required language versions;
* It is out-of-date.

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,12 +1,36 @@
-#!/usr/bin/env bash
+#!/bin/sh
+set -e
 
-if ! hash bundle 2>/dev/null; then
-  gem install bundler
+if ! command -v asdf >/dev/null 2>&1; then
+  cat >&2 <<EOS
+asdf-vm not found
+
+This project uses asdf-vm for language version management. Make sure it is
+correctly installed and retry setting up the project.
+EOS
+  exit 1
 fi
 
-npm install
-$(npm bin)/bower install
-(bundle check &>/dev/null) || bundle install
+echo '- Installing required language versions'
+asdf install
 
+if ! command -v bundle >/dev/null 2>&1; then
+  echo '- Installing Ruby bundler'
+  gem install bundler
+  asdf reshim ruby
+fi
+
+echo '- Installing Ruby dependencies'
+bundle install
+
+echo '- Installing Javascript dependencies'
+npm install
+
+echo '- Installing Bower packages'
+npx bower install
+
+echo '- Initializing Git submodules'
 git submodule init
+
+echo '- Updating Git submodules'
 git submodule update
